#!/usr/bin/env python3
## This file is used to generate database files
import os
import jsonpickle

from src import rpg

def build_object(cls, id, data):
  data['id'] = id
  object = cls(**data)
  return object

def build(cls, data):
  objects = []
  for i in range(0, len(data)):
    objects.append(build_object(cls, i + 1, data[i]))
  return [None] + objects

db = {
  "jobs": build(rpg.Job, [
    {
      "name": "Paladin",
      "sprite_name": "paladin",
      "sprite_cols": 6,
      "sprite_rows": 7,
      "description": [
        "An expert in melee combat.",
        "Ideal for new players.",
        ""
      ],
      "bases":  [50, 10, 16, 12, 5, 5, 5],
      "growth": [ 5,  2,  3, 2, 2, 2, 1],
      "motions": {
        "idle": list(range(1, 7)),
        "hurt": list(range(18, 23)),
        "atk1": list(range(6, 18)),
        "atk2": list(range(22, 40)),
      },
      "skill_ids": [3, 4, 1, 2],
    },
    {
      "name": "Ranger",
      "sprite_name": "ranger",
      "sprite_cols": 8,
      "sprite_rows": 6,
      "description": [
        "A jack of all trades class.",
        "Recommended for intermediate",
        "players."
      ],
      "bases":  [35, 15, 10, 8, 10, 8, 10],
      "growth": [ 3,  2, 2, 1, 2, 1,  2],
      "motions": {
        "idle": list(range(0, 8)),
        "hurt": list(range(42, 46)),  
        "atk1": list(range(8, 19)),
        "atk2": list(range(19, 42)),
      },
      "skill_ids": [5, 6, 1, 2],
    },
    {
      "name": "Wizard",
      "sprite_name": "wizard",
      "sprite_rows": 6,
      "sprite_cols": 6,
      "description": [
        "An expert on magic.",
        "Recommended for advance",
        "players."
      ],
      "bases":  [30, 20, 5, 5, 14, 8, 8],
      "growth": [ 2,  4, 1, 1,  3, 3, 3],
      "motions": {
        "idle": list(range(0, 6)),
        "hurt": list(range(33, 38)),
        "atk1": list(range(6, 14)),
        "atk2": list(range(13, 32)),   
      },
      "skill_ids": [7, 8, 1, 2],
    },
  ]),
  "enemies": build(rpg.Enemy, [
    {
      "name": "Bat",
      "base_exp": 5,
      "exp_growth": 3,
      "base_gold": 1,
      "gold_growth": 1,   
      "sprite_name": "bat",
      "sprite_rows": 4,
      "sprite_cols": 5,    
      "bases":  [10, 0, 7, 5, 7, 5, 5],
      "growth": [ 3, 0, 3, 1, 2, 4, 8],
      "motions": {
        "idle": list(range(0, 6)),
        "hurt": [17, 17, 18, 18, 18],
        "atk1": list(range(5, 10)),
        "atk2": list(range(10, 15)),
      },            
      "skill_ids": [9, 10]
    },
    {
      "name": "Boar",
      "base_exp": 8,
      "exp_growth": 4,
      "base_gold": 1,
      "gold_growth": 3,   
      "sprite_name": "boar",
      "sprite_rows": 6,
      "sprite_cols": 6,    
      "bases":  [60, 0, 15, 10, 4, 4, 8],
      "growth": [ 5, 0,  5,  3, 2, 5, 3],
      "motions": {
        "idle": [0, 1, 2, 3, 4, 5],
        "hurt": [19, 20, 21, 22, 23],
        "atk1": list(range(6, 20)),
        "atk2": list(range(23, 35)),
      },            
      "skill_ids": [11, 12]
    },
    {
      "name": "Dragon",
      "base_exp": 10,
      "exp_growth": 5,
      "base_gold": 10,
      "gold_growth": 14,   
      "sprite_name": "dragon",
      "sprite_rows": 5,
      "sprite_cols": 5,    
      "bases": [80,  0, 30, 20, 40, 15, 20],
      "growth": [10, 0,  5,  5,  5,  5,  5],
      "motions": {
        "idle": [0, 1, 2, 3, 4],
        "hurt": [20, 20, 21, 21, 21],
        "atk1": list(range(5, 12)),
        "atk2": list(range(12, 20)),
      },           
      "skill_ids": [13, 14],
      "battle_name": "danger",
    },
    {
      "name": "Ghost",
      "base_exp": 1,
      "exp_growth": 2,
      "base_gold": 3,
      "gold_growth": 4,   
      "sprite_name": "ghost",
      "sprite_rows": 5,
      "sprite_cols": 6,    
      "bases":  [10, 0, 1, 30, 10, 5, 20],
      "growth": [ 5, 0, 5, 20,  3, 1, 10],
      "motions": {
        "idle": [0, 1, 2, 3, 4, 5],
        "hurt": [26, 27, 28, 29],
        "atk1": list(range(6, 12)),
        "atk2": list(range(12, 25)),     
      },         
      "skill_ids": [15, 16],
      "battle_name": "scary",
    },
    {
      "name": "Kobold",
      "base_exp": 8,
      "exp_growth": 2,
      "base_gold": 7,
      "gold_growth": 4,   
      "sprite_name": "kobold",
      "sprite_rows": 3,
      "sprite_cols": 5,    
      "bases":  [30, 0, 20, 10, 5, 8, 15],
      "growth": [ 3, 0,  4,  5, 3, 4,  5],
      "motions": {
        "idle": [0, 1, 2, 3, 4],
        "hurt": [13, 13, 14, 14, 14],
        "atk1": list(range(5, 11)),
        "atk2": list(range(5, 11)),
      },          
      "skill_ids": [17, 18]
    },
    {
      "name": "Mushroom",
      "base_exp": 3,
      "exp_growth": 3,
      "base_gold": 2,
      "gold_growth": 1,   
      "sprite_name": "mushroom",
      "sprite_rows": 7,
      "sprite_cols": 5,    
      "bases": [20, 0, 10, 5, 5, 5, 10],
      "growth": [ 3, 0, 1, 3, 3, 3,  4],
      "motions": {
        "idle": [0, 1, 2, 3, 4, 5, 6, 7, 8],
        "hurt": [29, 30, 31, 32],
        "atk1": list(range(8, 23)),
        "atk2": list(range(20, 30)), 
      },       
      "skill_ids": [19, 20]
    },
    {
      "name": "Slime",
      "base_exp": 3,
      "exp_growth": 4,
      "base_gold": 2,
      "gold_growth": 1,   
      "sprite_name": "slime",
      "sprite_rows": 5,
      "sprite_cols": 5,    
      "bases": [50, 0, 10, 5, 10, 1, 20],
      "growth": [ 8, 0, 2, 3, 1, 1, 3],
      "motions": {
        "idle": [0, 1, 2, 3, 4],
        "hurt": [22, 22, 23, 23, 23],
        "atk1": list(range(5, 10)),
        "atk2": list(range(10, 22)),
      },           
      "skill_ids": [21, 22]
    },
  ]),
  "skills": build(rpg.Skill, [
    {
      "name": "Heal",
      "icon_index": 32,
      "motion": "idle",
      "animation_id": 2,
      "animation_wait": 1,
      "type": "heal",
      "mp_cost": 3,
      "formula": "user.spirit * 3 + 5",
      "variance": 20,
    },
    {
      "name": "Escape",
      "icon_index": 37,
      "motion": "idle",
      "animation_id": 0,
      "animation_wait": 0,
      "type": "escape",
      "mp_cost": 0,
      "formula": "0",
      "variance": 20,
    },
    {
      "name": "Slash",
      "icon_index": 13,
      "motion": "atk1",
      "animation_id": 6,
      "animation_wait": 6,
      "type": "damage",
      "mp_cost": 0,
      "formula": "(user.attack - target.defense) * 2",
      "variance": 20,
    },
    {
      "name": "Smite",
      "icon_index": 34,
      "motion": "atk2",
      "animation_id": 1,
      "animation_wait": 14,
      "animation_loops": 2,
      "type": "damage",
      "mp_cost": 5,
      "formula": "(user.attack * 3 + user.intelligence) - target.defense",
      "variance": 20,
    },
    {
      "name": "Attack",
      "icon_index": 13,
      "motion": "atk1",
      "animation_id": 3,
      "animation_wait": 6,
      "type": "damage",
      "mp_cost": 0,
      "formula": "(user.attack * 3 - target.defense * 2) * 2",
      "variance": 20,
    },
    {
      "name": "Mana Arrow",
      "icon_index": 39,
      "motion": "atk2",
      "animation_id": 3,
      "animation_wait": 22,
      "type": "damage",
      "mp_cost": 5,
      "formula": "(user.attack + user.intelligence * 2 - target.spirit) * 3",
      "variance": 20,
    },
    {
      "name": "Bash",
      "icon_index": 13,
      "motion": "atk1",
      "animation_id": 1,
      "animation_wait": 3,
      "type": "damage",
      "mp_cost": 0,
      "formula": "(user.attack - target.defense * 2) * 2",
      "variance": 20,
    },
    {
      "name": "Fireball",
      "icon_index": 16,
      "motion": "atk2",
      "animation_id": 4,
      "animation_wait": 15,
      "type": "damage",
      "mp_cost": 5,
      "formula": "(user.intelligence * 3 - user.spirit) * 2",
      "variance": 20,
    },
    {
      "name": "Attack (Bat)",
      "icon_index": 0,
      "motion": "atk1",
      "animation_id": 7,
      "animation_wait": 3,
      "type": "damage",
      "mp_cost": 0,
      "formula": "(user.attack - target.defense) * 2",
      "variance": 20,
    },
    {
      "name": "Magic (Bat)",
      "icon_index": 0,
      "motion": "atk2",
      "animation_id": 1,
      "animation_wait": 4,
      "type": "damage",
      "mp_cost": 0,
      "formula": "(user.attack + user.intelligence - target.defense) * 2",
      "variance": 15,
    },
    {
      "name": "Attack (Boar)",
      "icon_index": 0,
      "motion": "atk1",
      "animation_id": 1,
      "animation_wait": 9,
      "type": "damage",
      "mp_cost": 0,
      "formula": "(user.attack - target.defense) * 2",
      "variance": 10,
    },
    {
      "name": "Magic (Boar)",
      "icon_index": 0,
      "motion": "atk2",
      "animation_id": 1,
      "animation_wait": 6,
      "type": "damage",
      "mp_cost": 0,
      "formula": "(user.attack * 3 + user.spirit - target.defense) * 2",
      "variance": 30,
    },
    {
      "name": "Attack (Dragon)",
      "icon_index": 0,
      "motion": "atk1",
      "animation_id": 7,
      "animation_wait": 4,
      "type": "damage",
      "mp_cost": 0,
      "formula": "(user.attack * 2 - target.defense) * 2",
      "variance": 20,
    },
    {
      "name": "Magic (Dragon)",
      "icon_index": 0,
      "motion": "atk2",
      "animation_id": 4,
      "animation_wait": 4,
      "type": "damage",
      "mp_cost": 0,
      "formula": "(user.intelligence * 5 - target.spirit * 2) * 2",
      "variance": 50,
    },
    {
      "name": "Attack (Ghost)",
      "icon_index": 0,
      "motion": "atk1",
      "animation_id": 1,
      "animation_wait": 3,
      "type": "damage",
      "mp_cost": 0,
      "formula": "(user.attack + user.intelligence * 2 - target.defense * 2) * 2",
      "variance": 20,
    },
    {
      "name": "Magic Ghost",
      "icon_index": 0,
      "motion": "atk2",
      "animation_id": 8,
      "animation_wait": 9,
      "type": "damage",
      "mp_cost": 0,
      "formula": "0",
      "variance": 15,
    },
    {
      "name": "Attack (Kobold)",
      "icon_index": 0,
      "motion": "atk1",
      "animation_id": 5,
      "animation_wait": 4,
      "type": "damage",
      "mp_cost": 0,
      "formula": "(user.attack - target.defense) * 2",
      "variance": 25,
    },
    {
      "name": "Heal (Kobold)",
      "icon_index": 0,
      "motion": "idle",
      "animation_id": 0,
      "animation_wait": 0,
      "type": "heal",
      "mp_cost": 0,
      "formula": "user.wis * 2 + 3",
      "variance": 10,
    },
    {
      "name": "Attack (Mushroom)",
      "icon_index": 0,
      "motion": "atk1",
      "animation_id": 1,
      "animation_wait": 8,
      "type": "damage",
      "mp_cost": 0,
      "formula": "(user.attack - target.defense) * 2",
      "variance": 15,
    },
    {
      "name": "Magic (Mushroom)",
      "icon_index": 0,
      "motion": "atk2",
      "animation_id": 1,
      "animation_wait": 9,
      "type": "damage",
      "mp_cost": 0,
      "formula": "(user.intelligence - target.defense) * 3",
      "variance": 20,
    },
        {
      "name": "Attack (Slime)",
      "icon_index": 0,
      "motion": "atk1",
      "animation_id": 1,
      "animation_wait": 3,
      "type": "damage",
      "mp_cost": 0,
      "formula": "(user.attack - target.defense)",
      "variance": 10,
    },
    {
      "name": "Magic (Slime)",
      "icon_index": 0,
      "motion": "atk2",
      "animation_id": 1,
      "animation_wait": 6,
      "type": "damage",
      "mp_cost": 0,
      "formula": "(user.attack * 3 - target.defense * 2) * 2",
      "variance": 20,
    }
  ]),
  "animations": build(rpg.Animation, [
    {
      "name": "Blow",
      "frame_count": 6,
      "image_name": "blow",
      "sfx_name": "blow",
    },
    {
      "name": "Heal",
      "frame_count": 7,
      "image_name": "heal",
      "sfx_name": "heal",
    },
    {
      "name": "Arrow",
      "frame_count": 5,
      "image_name": "arrow",
      "sfx_name": "blow",
    },
    {
      "name": "Fire",
      "frame_count": 4,
      "image_name": "fire",
      "sfx_name": "blow",
    },
    {
      "name": "Slash",
      "frame_count": 5,
      "image_name": "slash",
      "sfx_name": "slash",
    },
    {
      "name": "Pierce",
      "frame_count": 6,
      "image_name": "pierce",
      "sfx_name": "blow",
    },
    {
      "name": "Claw",
      "frame_count": 6,
      "image_name": "claw",
      "sfx_name": "slash",
    },
    {
      "name": "Beam",
      "frame_count": 6,
      "image_name": "beam",
      "sfx_name": "beam",
    },
    {
      "name": "Shiny mon",
      "frame_count": 5,
      "image_name": "shiny",
      "sfx_name": "shiny",
    },
  ]),
  "locations": build(rpg.Location, [
    {
      "name": "Grassland",
      "background_name": "grassland",
      "enemy_ids": [1, 1, 1, 1, 1, 1, 1, 1, 1, 7],
    },
    {
      "name": "Beach",
      "background_name": "beach",
      "enemy_ids": [4, 7, 7, 7, 7, 7, 7, 7, 7, 1],
    },
    {
      "name": "Dessert",
      "background_name": "dessert",
      "enemy_ids": [1, 1, 1, 1, 1, 4, 4, 4, 5],
      "music_name": "dessert",
    },
    {
      "name": "Forest",
      "background_name": "forest",
      "enemy_ids": [1, 2, 2, 2, 2, 5, 5, 5, 5, 6],
    },
    {
      "name": "Snow",
      "background_name": "snow",
      "enemy_ids": [1, 1, 2, 2, 2, 3, 3, 3, 3, 4],
      "music_name": "snow"
    },
  ]),
}

def write_file(name, data):
  with open(name, "w") as file:
    file.write(jsonpickle.encode(data))

os.makedirs("data", exist_ok=True)
for file in db.keys():
  write_file(f"data/{file}.json", db[file])